"""add_indexes_and_rename_model_metadata

Revision ID: 3f3875b845f8
Revises: 001_initial
Create Date: 2025-10-25 03:25:49.478898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3875b845f8'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_model_versions', sa.Column('model_metadata', sa.JSON(), nullable=True, comment='Additional model metadata'))
    op.create_index(op.f('ix_ml_model_versions_is_active'), 'ml_model_versions', ['is_active'], unique=False)
    op.drop_column('ml_model_versions', 'metadata')
    op.create_index(op.f('ix_scan_history_date'), 'scan_history', ['date'], unique=False)
    op.create_index(op.f('ix_scan_history_scan_id'), 'scan_history', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scans_correlation_id'), 'scans', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_file_hash'), 'scans', ['file_hash'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_category'), 'vulnerabilities', ['category'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_resource'), 'vulnerabilities', ['resource'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_resource'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_category'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_file_hash'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_correlation_id'), table_name='scans')
    op.drop_index(op.f('ix_scan_history_scan_id'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_date'), table_name='scan_history')
    op.add_column('ml_model_versions', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional model metadata'))
    op.drop_index(op.f('ix_ml_model_versions_is_active'), table_name='ml_model_versions')
    op.drop_column('ml_model_versions', 'model_metadata')
    # ### end Alembic commands ###
